# -*- coding: utf-8 -*-
"""All programs  48 classes -21  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9UVs9Qv7w61n5H64Ay2WxejL-yP-zKA
"""

# Lesson 2
# Print Even numbers from 60 - 100
num=60

while (num<=100):
     print(num)
     num=num+2

# Solution
# Step 1: Ask the user to enter the number of wins, draws and losses
wins=int(input('Enter the number of wins'))
draws=int(input('Enter the number of draws'))
loses=int(input('Enter the number of losses'))
# Step 2: Initialize 'total' variable with '0'
total=0
# Step 3: Calculate the win points by multiplying the number of wins by 3
win_points= wins*3
# Step 4: Add the values stored in 'win_points' and draws and store the result in 'total'
total=win_points + draws
# Step 5: Print the value stored in variable 'total'
print(total)

# Step 1: Get the number of switches as an integer and store it in a variable.
switches=10

# Step 2: Initialize 3 variables 'max_poss = 2', 'i = 1' & 'power = 1'
max_poss=2
i=1
power=1

# Step 3: Define a while loop with a condition to execute till the value of 'i <= switches'
while (i<=switches):
 # Step 4: Multiply 'max_poss' with 'power' and store the result in 'power'
 power=max_poss*power
 result=power

 # Increment the value of 'i' by '1'
 i=i+1

# Step 5: Print the total number of possible outcomes stored in 'power'
print(power)



# Lesson 3
# Write your code here
# Step 1: Accept user input.
num =int(input('enter the number'))
# Step 2: Define a function 'multiplier(n)' .
def multiplier(n):
      # Step 3: Inside the function, check if the number is negative, positive or 0
  if n<0:
    print('Sorry!','the number cannot be negative')
  elif n==0:
    print('The result is 1')
      # If the number is positive, perform Step 4 and Step 5
  elif n>0:
   mult=1
   while n>0:
    mult=(mult*n)
    n=n-1
   print(mult)
# Step 6: Call the 'multiplier()' function to execute
multiplier(num)

# Write your code here
# Step 1: Get the user input
num=int(input('enter a number'))
# Step 2: Initialize variable 'i'
i=1
# Step 3: Execute a 'while' loop 10 times
while i<=10:
  # Step 4: Multiply the 'num' variable with 'i' variable and print its result. Increment the value of 'i' by 1
      print(num*i)
      i=i+1



# Lesson 5
# Write your code here
# Step 1: Accept a number from the user. Convert it into an integer and then store it in a variable 'num'
number=input('ask user to enter a number')
num=int(number)
# Step 2: Use if condition to check whether the number is even or odd using (%) operator
remainder= num % 2
if (remainder==0):
   num='even_number'
   print(number,'even_number')
else:
  print(number,'odd number')

# Write your code here
# Step 1: Define a function 'tri_area()'
def tri_area(base,height):
	# Step 2: Calculate area using the formula
  tri_area=(base *height)/2
	# Step 3: Return the calculated area
  return tri_area
# Step 4: Call the 'tri_area()' function
tri_area(4,8)

# Write your solution here
# Step 1: Define two lists `list1` and `list2`
list1=[2,3,4,8,5]
list2=[50,54]
# Step 2: Use `append()` to append second list with the first list
list2.append(list1)
# Step 3: Print `list1` to get the new list
print(list2)



# Lesson 6
#Write your solution here
# Step 1: Create a function 'series(n)'
def series(n):
  # Step 2: Initialize 'n1' and 'n2' variables
    n1=0
    n2=1
  # Step 3: Initialize 'count' variable
    count=0
  # Step 4: Check whether 'n'<=0
    if n<=0:
       print('Please enter a positive_number')
    # Step 5: Run a while loop till 'count' < 'n'
    else:
        while count<n:
    # Perform Step 6
              print(n1)
              nth=n1+n2
              n1=n2
              n2=nth
              count=count+1
# Step 7: Call 'series()' function
series(5)

def missing_num(lst):
   print(lst)
   for i in range(1,11):
    if i in lst:
      i=i+1
    else:
      print(i)
      break
missing_num([2,3,4,5,7,6,9,8,10])



# lesson 7
# Write your code here
# Step 1: Accept two numbers from the user and store them 'num1' and 'num2' variables
num1=int(input(' enter a number'))
num2=int(input(' enter a number'))

# Swapping values of variables begins
# Step 2: Declare a temporary variable 'temp' and assign the value of 'num1' to it
temp=num1
# Step 3: Assign value of 'num2' to 'num1'
num1=num2
# Step 4: Assign value of 'temp' to 'num2'
num2=temp
# Step 5: Print the values of 'num1' and 'num2' after swapping
print(num1)
print(num2)

# Write your code here
# Step 1: Define a list with some random numbers
num_list=[1,2,3,4,5,6,7,8,9,10]
# Step 2: Get the length of the list using 'len()' function
length=len(num_list)
# Step 3: Initialize two variables 'i' and 'result'
i=0
result=1
# Step 4: Iterate while loop till the length of the list
while i<length:
  # Step 5: Multiply the 'result' variable with each element of the list. Use list indexing
  result=result * num_list[i]
  # Increment 'i' variable
  i=i+1
# Step 6: Print the result
print(result)



# Write your code here
# Step 1: Import numpy module
import numpy as np
# Step 2: Declare a variable 'x' to store the result and use 'arange()' and 'reshape()' functions
arr=np.arange(2,11)
x=arr.reshape(3,3)
# Step 3: Print te variable 'x' to see the output
print(x)

# Write your code here
# Import numpy module
import numpy as np
# Create a NumPy array containing a list of numbers
my_arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Print the dimension of the array
print(my_arr.ndim)
# Change the dimension of the array into a 3 X 3
my_arr=my_arr.reshape(3,3)
# Print the array
print(my_arr)
# Convert the NumPy array into a Python list
my_list=list(my_arr)
# Use type() function to verify the conversion
type(my_list)

# Write your solution here
import numpy as np
list1 = [4, 16, 9, 1, 25]
print(list1)
sqrt=np.sqrt(list1)
print(sqrt)



# Lesson 10
# Write a program to create Null array of size 10 and update the sixth value to 11.
import numpy as np
null_arr= np.zeros(10)
print(null_arr)
print(' update the sixth value to 11')
null_arr[5]=11
print(null_arr)

# Write a program to populate a number list divisible by 5 in a range of 0 - 49
multiples_of_five =[i for i in range(0,49)if i%5==0]
print(multiples_of_five)

# Write a program to convert a list into one dimensional NumPy array
lst = [12.23, 13.32, 100, 36.32]
print(lst)
lst1=np.array(lst)
print(lst1)



#Lesson 11
# Write your code here
# Step 1: Define a function with list of items and item to be searched as parameters
def get_indices(element_list, key):
	result_list = []
	# Step 2: Declare an empty list to hold the result

	# Step 3: Create 'for' loop which runs till the length of the list
      # Inside a for loop, check whether each element in the list is matching with the searched element
      # If it matches, append the blank list with the element's index number

  # Step 4: Return the result

# Step 5: Call the function

	for i in range(len(element_list)):
		if element_list[i] == key:
			result_list.append(i)
	return result_list

get_indices([1, 5, 5, 4, 3, 2, 5, 2, 7], 2)

# Write your code here
# Step 1: Declare two lists with some random numbers
list1=[10, 20, 30, 40, 50, 60]
list2=[60, 50, 40, 30, 20, 10]
# Step 2: Declare an empty list for storing the result
my_list=[]
# Step 3: Start a 'for' loop which iterates till the length of the list
for i in range(len(list1)):
# Step 4: Inside 'for' loop, check whether first list element is greater than second list element
    if list1[i] > list2[i]:
    #If it is, then subtract the respective elements and append the result to the empty list using 'append()' function, else just append the first list element
        my_list.append(list1[i] - list2[i])
    else:
        my_list.append(list1[i])
# Step 5: Print both original lists
print("Original lists :")
print(list1)
print(list2)
# Step 6: Print the third list where the new values are stored
print("result :",my_list)

# Write your code here
# Step 1: Import numpy module
import numpy as np
# Step 2: Create a list of temperatures in Fahrenheit degree
fahrenheit=[ 0, 32, 45.21]
# Step 3: Use array() function to convert list into array. Print this array
fahrenheit = np.array(fahrenheit)

celsius = (fahrenheit - 32) / 1.8
celsius
np.round(celsius,2)



#Lesson 12
# Write a program to find prime numbers from 2 to 50.
lower= 2
upper= 50
print("prime numbers from 2 to 50")

for num in range(lower,upper + 1):
  if num > 1:
    for i in range(2,num):
        if (num % i) == 0:
            break
    else:
         print(num)

# Print n -digit number
def num_generator(n):
  req_num=0
  count=n-1
  while count>=0:
    req_num=req_num  + (10** count) * n
    count=count-1
  return req_num
for n in range(1,10):
    print(num_generator(n), "=", n)



#lesson 13
# Create Pandas series
import random
import pandas as pd
import numpy as np
numbers= np.random.randint(130,145,size=40)
print(numbers)

# Calculate the mean and median value
np.mean(numbers)



np.median(numbers)

np.min(numbers)

np.max(numbers)

# Arrange the values in descending order and print the last five rows
numbers = [139 , 137, 138 , 1, 37 , 139, 133, 137, 134 , 133, 13, 136, 138 , 141 , 144, 143 , 143 , 136 , 134]
numbers.sort(reverse=True)
print("Descending order", numbers)
print()

a = 5
last_five = numbers[-a:]
print("last_five",last_five)

# Two lines are parallel or not
def parallel_lines(line1,line2):
  return line1[0]/line1[1]==line2[0]/line2[1]
print(parallel_lines([2,3,4],[4,6,8]))
print(parallel_lines([2,6,4],[4,-6,8]))



# Lesson 14
# Check for missing values in the above Pandas series.
NBA_players_df="https://media.geeksforgeeks.org/wp-content/uploads/nba.csv"
NBA_players_df=pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
print(NBA_players_df)
NBA_players_df.isnull()

# Create pandas series for the player 'Avery Bradley'
import pandas as pd
avery_bradley=NBA_players_df.iloc[0,:]
print(avery_bradley)

# Number of solutions for a quadratic equation
import random
import pandas as pd
print("general form:-ax**2 + bx +c=0")
a=int(input("enter a number"))
b=int(input("enter a number"))
c=int(input("enter a number"))
d=(b**2)-(4*a*c)
if d==0:
  print("one real roots")
elif d<0:
  print("no roots")
elif d>0:
   print("two real roots")

print(d)



# Lesson 16
# Check if the Square root of the First number is Equal to the Cube root of the Second number
from math import sqrt
a = 0
b = 0
def checker(a,b):
    a = int(input("Enter a Square number :"))
    x = sqrt(a)
    print(x)

    b = int(input("Enter a cube number :"))
    y = b**(1/3)
    print(y)

    if x==y:
        print("square root is equal to cube root")
        return "True"
    else:
        print("square root is not equal to cube root")
        return "False"
checker(a,b)

# Print sum of series
import numpy as np
def sum_series(number):
    num = 1
    while num <= number:
        sum = 0
        num_list = []
        for i in range(num):
            sum = sum +(num*pow(10,i))
            num_list.append(sum)

        num_array= np.array(num_list)
        print(num_array.sum())
        num = num+1
sum_series(9)



# Lesson 17



# Lesson 18
# Write your solution here:

number = int(input("Please Enter any Number: "))

last_digit1 = number % 10

print("The Last Digit in a Given Number %d = %d" %(number, last_digit1))


num1= int(input("Please Enter any Number: "))

last_digit2 = num1 % 10

print("The Last Digit in a Given Number %d = %d" %(num1, last_digit2))

num2 = int(input("Please Enter any Number: "))

last_digit3 = num2 % 10

print("The Last Digit in a Given Number %d = %d" %(num2, last_digit3))

print()
if last_digit1 * last_digit2 == last_digit3:
     print("True")
else:
    print("False")

# Write your solution here
a = int(input("enter a number"))
sum = 1
for i in range(1,a):
    sum = sum + 5 * i
print(sum)

a=int(input("enter a number"))
sum = 1
for i in range(1,a):
    sum = sum + 5 * i
print(sum)



#Lesson 19
# Create Scatter plot with Unemployment Rate on X-axis and Stock Price on Y-axis
import matplotlib.pyplot as plt
import numpy as np
# import modules

# Create two lists, one for Unemployment Rate and one for Stock Price
plt.figure(figsize=(20,5))
x_value = [6.2, 5.8, 5.7, 5.5, 5.3, 5.2, 5.9 ]
y_value = [1600, 1500, 1530, 1540, 1620, 1534, 1565]

# Create Scatter plot
plt.grid()

plt.xlabel('Unemployment Rate ------>')
plt.ylabel('Stock Price ------------->')
plt.scatter(x_value, y_value)
plt.show()

# Create Line plot with Year on X-axis and Unemployment Rate on Y-axis

# Create two lists, one for Year and one for Unemployment Rate
plt.figure(figsize=(20,5))
year = np.arange(1920,2020,10)
unemployment_rate = [9.8, 12, 8, 7.2, 6.9, 7, 6.5, 6.2, 5.5, 6.3]
# Create the line plot
plt.grid()
plt.plot(year,unemployment_rate)
plt.xlabel("Year ------------->")
plt.ylabel("Unemplument_Rate ---------->")
plt.show()

# Write your code here
def tower_hanoi(disks):
    n = 5
    disks = 2**n - 1
    return disks
tower_hanoi(2)



#Lesson 21
# Write your code here
number = int(input("Enter the integer number: "))
revs_number = 0
x = number
while (number > 0):
    remainder = number % 10
    revs_number = (revs_number * 10) + remainder
    number = number // 10

print(revs_number)

if (x == revs_number):
    print("The number is a palindrome")
else:
    print("The number is not a palindrome")

# Write your solution here
my_list = [1, 9, 8, 8, 7, 6, 1, 6]

unique_list=[]

for i in my_list:
    if (my_list.count(i)) == 1:
       print([i],end = " ")



#Lesson 22
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(20,5))
sns.boxplot(box_0)
plt.show()

# Create a Boxplot for 'size' column with respect to 'tip' column
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(20,5))
sns.boxplot(data_set['size'],data_set['tip'])
plt.show()



# lesson 23
num = int(input("Enter a number : "))
	# create while loop and check whether the number is prime or not,
while True:
    for i in range(2,num):
        if (num % i)==0:
            print(num,"not a prime number")
            num = num + 1
            break
    else:
        print(num,"prime number")
        break
    3# if the number is not a prime number, increment the value passed in the function until we get the next prime number.
	# Specify this condition of while loop using List Comprehension
else:
    print(num,"is not a prime number")

# Write your code here
lower = int(input("Enter the lower value : "))
upper = int(input("Enter the upper value : "))
for i in range(lower, upper+1):
    if i > 1:
        if (i % 2 !=0):
            print(i)

# Lesson 24
import folium
Statue_of_Liberty = folium.Map(location = [40.6892, -74.0445])
folium.Marker(location = [40.6892, -74.0445],popup= "Liberty Island").add_to(Statue_of_Liberty)
Statue_of_Liberty

# Create a Chennai map (coordinates 13.0556, 80.2837) and add a circular marker for the Marina Beach on the map.
import folium
Chennai_map = folium.Map(location = [13.0556, 80.2837])
folium.Marker(location = [13.0556, 80.2837],popup= "Marina Beach").add_to(Chennai_map)
folium.Circle(location=[13.0556, 80.2837],radius =60,popup= "Marina Beach").add_to(Chennai_map)
folium.CircleMarker(location=[13.0556, 80.2837],radius =60,popup= "Marina Beach").add_to(Chennai_map)
Chennai_map

# Lesson 25



# Lesoon 26
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(20,5))
sns.countplot(x ='sex',data = tif_df)
plt.show()

# Write your solution here
# Define the function 'sum_fractions()' which accepts a list containing more than 1 sublists as an argument
# Call the function
def func1(mylist):
    total = 0
    index = 0
    for row in range(2):
        for col in range(2):
            number = mylist[row][0]/ mylist[row][1]
            total = total + number

    print(total)
func1([[18,13],[4,5]])
print("After round off : ",round(2.18))



#Lesson 27
# Write a function to read the billable days of an employee and return the bonus he/she has obtained in that quarter.
def calculate_bonus(n):
    bonus = 0
    if  n <= 32:
        b = bonus * 32
        print("Bonus :", b)
    elif n <= 40 :
        c  = bonus * 32  + 5 * 325
        print("Bonus : ",c)
    elif n <= 48:
        d = bonus * 32  + 8 * 325 + 5 * 550
        print("Bonus : ",d)
    elif n <= 100:
        e = bonus * 32 + 8 * 325 + 5 * 550 + 5 * 600
        print("Bonus  will more than 8200 : ",e)

# Write your solution here
row = int(input("Enter number of rows :"))
col = int(input("Enter number of columns :"))
for i in range(row):
    for j in range(col):
        if i== 0 or i== (row-1) or j== 0 or j==(col-1) :
           print(" # ", end=" ")
        else:
           print("   ",end=" ")
    print()



# Lesson 28
plt.figure(figsize=(10,5))
sns.countplot(x = 'sex', data = df)
plt.title('Gender classification')
plt.show()

# Write a program to find kempner of n
def kempner(n, i= 1, total=1):
    if total % n == 0:
        return max(1, i- 1)
    else:
        return kempner(n,i+1, total*i)

kempner(10)



# Lesson 29
# Counts of each value in the 'EDUCATION' column.
df['EDUCATION'].value_counts()

# Replace the unwanted values in the 'EDUCATION' column. Ignore if there are none.
df.loc[df['EDUCATION'] == 0, 'EDUCATION'] = 5

# Count plot for the 'EDUCATION' column using the 'countplot()' function of 'seaborn' module.
plt.figure(figsize=(20,5))
sns.countplot(x=education)
plt.grid()
plt.show()

# Replace the unwanted values ('0') in the 'MARRIAGE' column with '3'. Ignore if there are none.
df.loc[df['MARRIAGE'] == 0, 'MARRIAGE'] = 3

# Count plot for the 'MARRIAGE' column.
plt.figure(figsize=(20,5))
sns.countplot(x= marriage)
plt.show()

plt.figure(figsize=(20,5))
sns.boxplot(df['AGE'])
plt.show()

# Histogram for the 'AGE' column using 'distplot()' function from the 'seaborn' module.
plt.figure(figsize=(20,5))
sns.distplot(df['AGE'])
plt.grid()
plt.show()

# Histogram for the 'LIMIT_BAL' column using 'distplot()' function from the 'seaborn' module.
plt.figure(figsize=(20,5))
sns.distplot(df['LIMIT_BAL'])
plt.grid()
plt.show()

# Histogram (having 50 bins) for the 'LIMIT_BAL' column using 'hist()' function from the 'matplotlib.pyplot' module.
plt.figure(figsize=(20,5))
plt.hist(df['LIMIT_BAL'],bins = 50)
plt.grid()
plt.show()



# Lesson 30
# Create a python dictionary holding your friend's favourite hobby and sport
our_hobbies = {
                'Aniket':{'hobby':'reading books','sport':'Cricket'},
                'Vishal':{'hobby':'Eating different foods','sport':'Football'},
                'Sumant':{'hobby':'Roaming in the nature','sport':'Bolleyball'},
                'Anand':{'hobby':'Reading Businnies retated books','sport':'Cricket'},
                ' Rahul':{'hobby':'cycling','sport':'Badmintion'}

}
print(our_hobbies)

# Create beginning and end pairs
list1 = [1, 2, 3, 4, 5, 6, 7]
length = len(list1)
new_list =[]
two_d_list = []
for i in range(0,4):
    first_pair = list1[i]
    second_pair = list1[length - 1 - i]
    new_list = [first_pair, second_pair]
    two_d_list.append(new_list)
two_d_list

list1 = [1, 2, 3, 4, 5, 6]
length = len(list1)
new_list =[]
two_d_list = []
for i in range(0,3):
    first_pair = list1[i]
    second_pair = list1[length - 1 - i]
    new_list = [first_pair, second_pair]
    two_d_list.append(new_list)
two_d_list



#Lesson 31
# Write your solution here
get_student_names = ({
  "Student 1" : "Steve",
  "Student 2" : "Becky",
  "Student 3" : "John"
})
names = list(get_student_names.values())
print(names)

# Write your solution here

list1 = [1, 2]
list2 = [5, 1]
def list12(list1,list2):
    result = []
    for x in range(len(list1)):
        if list1[x] in list2:
            result = True
            return result

        else :
            result = False
            return result
print(list12(list1,list2))

# Write your solution here

list1 = [1, 2]
list2 = [5, 5]
def list12(list1,list2):
    result = []
    for x in range(len(list1)):
        if list1[x] in list2:
            result = True
            return result

        else :
            result = False
            return result
print(list12(list1,list2))



# Lesson 32
# Creating the empty 'cust_data' dictionary and the 'new_user_attributes' list.
cust_data = {}
new_user_attributes = ['name', 'address', 'phone num', 'govt id', 'amount']

import random
acc_num = random.randint(10000,99999)
print(acc_num)

# The 'new_user()' function to add a new user to the 'cust_data' dictionary.
import random

def new_user():
  # Step 1: Create a random five-digit account number and store it in 'acc_num' variable
    acc_num = random.randint(10000,99999)  # Write your code here

  # Step 2: Create an empty list and store it in the 'new_user_inputs' variable.
  # Write your code here
    new_user_inputs = []

  # Step 3: Prompting the user to enter all of their required details one-by-one and add them to the list new_user_input.
    for i in range(len(new_user_attributes)):
        user_input = input("Enter " + new_user_attributes[i] + ":\n")
        if new_user_attributes[i] == 'amount':
            new_user_inputs.append(int(user_input))
        else:
            new_user_inputs.append(user_input)

  # Step 4: Creating a dictionary for the new user and add it to the cust_data dictionary.
    cust_data[acc_num] = dict(zip(new_user_attributes, new_user_inputs))

  # Step 5: Display the message on successfull account creation to the user.
  # Write your code here

new_user()
cust_data

# The 'existing_user()' function to get the account details of an existing user from the 'cust_data' dictionary.
def existing_user(cust_data):
  # Step 1: Ask the user to enter the existing account number and store it as an integer.
    acc_num = int(input("Enter your account number"))# Write your code here
    while acc_num not in cust_data:
        acc_num = int(input("Not found. Please enter your correct account number:\n"))

  # Step 2: Print the welcome message to the user.
  # Write your code here
    print("Welcome !")
  # Step 3: Asking the user to select a valid choice.
    print("Enter 1 to check your balance.\nEnter 2 to withdraw an amount.\nEnter 3 to deposit an amount.")
    user_choice = input()
    while user_choice not in ['1','2','3']:
        print("\nInvalid input!")
        print("Enter 1 to check your balance.\nEnter 2 to withdraw an amount.\nEnter 3 to deposit an amount.")
        user_choice = input()

  # Step 4:
  # If 'user_choice == 1' then display the account balance i.e. 'cust_data[acc_num]['amount']'
    if user_choice == '1':
    # Write your code here
        print(cust_data[acc_num]['amount'])

  # Else if 'user_choice == 2' then subtract the withdrawal amount from the available balance.
    elif user_choice == '2':
        amt = int(input("\nEnter the amount to be withdrawn:\n"))
        if amt > cust_data[acc_num]['amount']:
            print("\nInsufficient balance.\nAvailable balance:", cust_data[acc_num]['amount'])
        else:
            new_amt = int(cust_data[acc_num]['amount']) - amt
            cust_data[acc_num]['amount'] = new_amt
            print("\nWithdrawal successful.\nAvailable Balance:", cust_data[acc_num]['amount'])

  # Else if 'user_choice == 3' then add the deposit amount to the available balance.
    elif user_choice == '3':
        amt = int(input("\nEnter the amount to be deposited:\n"))
        new_amt = int(cust_data[acc_num]['amount']) + amt
        cust_data[acc_num]['amount'] = new_amt
        print("\nDeposit successful.\nAvailable Balance:", cust_data[acc_num]['amount'])

existing_user(cust_data)

# Create an infinite while loop to run the application.
while True:
    valid_inputs = ['1','2','3']
    print("Welcome to the Horizon Bank!")
    print("\nEnter 1 if you are a new customer.\nEnter 2 if you are an existing customer.\nEnter 3 to terminate the application.")

    user_choice = input()
    while user_choice not in ['1','2','3']:
        print("Invalid input!")
        print("Enter 1 if you are a new customer.\nEnter 2 if you are an existing customer.\nEnter 3 to terminate the application.\n")
        user_choice = input()

  # If the user enters 1, then call the 'new_user()' function (to create a new account for the user and get their personal details).
  # Write your code here
    if user_choice == '1':
        new_user()
        print("Thank you ,for banking with us !")
        break

  # Else If the user enters 2, then call the 'existing_user()' function.
  # Write your code here
    elif user_choice == '2':
        existing_user(cust_data)
        print("Thank you ,for banking with us !")
        break

  # Else If the user enters 3, then terminate the application with the 'Thank you, for banking with us!' message.
  # Write your code here
    elif user_choice == '3':
        print("Thank you ,for banking with us !")
        break



# Lesson 33
# Write your code here
# Define a function which will take list as a parameter

  # This function returns only those items of list whose type is int. Specify this using list comprehension.
#Call the function
def my_list(lst):
    new_list = []
    for item in lst:
        if type(item )== int:
            new_list.append(item)
    return new_list
print(my_list([1, 2, "a", "b"]))

# Write your code here
# Create a function which takes a list as parameter.

	# Create an empty list

	# Using 'for' loop and 'if' statement, append every item to the empty list if it does not exist already in the empty list

	# After obtaining the list having no duplicate items, sort the list and return the list
# call the function


def list(lst):
    new_list = []
    for item in lst:
        if item not in new_list :
            new_list.append(item)
    new_list.sort()
    return new_list
print(list([3, 3, 3, 2, 1]))

# Write your code here
my_list =(1, 3, 5.78, 7.56, 'Python')
print("Tuples in reverse order : ")
for i in range(len(my_list)):
    print(-(i + 1), "is", my_list[len(my_list) - 1 - i])



# Lesson 34

# Tuple of random names.
names_tup = ('kevin', 'kamal', 'raj', 'prashant', 'albert', 'daniel', 'rahul')

# Print the contents of the 'names_tup' tuple.
print("Original tuples:",names_tup)
print()
# Convert the tuple into a list by passing the 'names_tup' tuple inside the 'list()' function.
# store it in another variable 'names_lst'.
name_lst = list(names_tup)
print("Original List : ", name_lst)
# Remove 'raj' from the 'names_lst' list using the 'remove()' function.
name_lst.remove("raj")
print("New list : ",name_lst)
print()
# Convert the list into a tuple by using the 'tuple()' function.
new_tuples= tuple(name_lst)
print("New tuples: ", new_tuples)
# Print the items of the tuple after reversing their order.
print("Reversed order of new tuples:",sorted(new_tuples,reverse= True))

# Tuple containing 30 random integers ranging between 100 and 250.
import random
rand_num = tuple([random.randint(100, 250) for i in range(30)])
rand_num

# Display the items of the 'rand_num' tuple in the descending order using the 'sorted()' function.
sorted(rand_num, reverse = True)

# Add Labels to the 'rand_num' tuple.
# Apply the 'tuple()' function on top of the 'enumerate()' function to add labels.
new_num = tuple(enumerate(rand_num))
new_num



# Lesson 35
my_quote = {1 : 'worromot rof epoH ,yadot rof eviL ,yadretsey morf nraeL',
            2 : 'elbissop si gnihtyreve dna flesruoy ni eveileB',
            3 : 'selcatsbo ton ,slaog no sucof ot si sseccus ot yek ehT',
            4 : 'selcatsbo ton ,slaog no sucof ot si sseccus ot yek ehT',
            5 : 'tnaw uoy worromoT eht dliub ot ytinutroppo eht si yadoT'}

# Write your code to reverse the quotes and display them in readable format
new_str = str(my_quote.values())
new_str

result = print("After Reversing the values : \n ",str(new_str[::-1]))
result

# Please look into this solution.
my_quote1 = {1 : 'worromot rof epoH ,yadot rof eviL ,yadretsey morf nraeL',
            2 : 'elbissop si gnihtyreve dna flesruoy ni eveileB',
            3 : 'selcatsbo ton ,slaog no sucof ot si sseccus ot yek ehT',
            4 : 'selcatsbo ton ,slaog no sucof ot si sseccus ot yek ehT',
            5 : 'tnaw uoy worromoT eht dliub ot ytinutroppo eht si yadoT'}

for quote in my_quote1.values():
    print(quote[::-1])

# Write your code here:
# Initiate a 'for()' loop in 'range(1,6)'
    # Convert the temporary variable into a string using the 'str()' function and multiply it with itself.
for i in range(1,6):
    for k in range(i):
        print(i,end="")
    print(" ")



# Lesson 36
# Program to count the number of words whose length is 2 or more and the first and last character are the same
# Define a function which accepts a list as input
def match_words(words):
  # Initialize a variable 'count' to 0 to count the number of words
  count = 0
  # Use 'for' loop to iterate through each word of the list
  # Also check whether first and last character of each word is same using string indexing. If they are same increase the value of 'count' by 1
  for word in words:
    if (len(word) > 2 and word[0] == word[-1]):
      count = count + 1
  return count

# Create a list of words
list_of_words = ['civic', 'organ', 'trust', 'rigid', 'erase', 'right']
# Call the function and pass this list as parameter
match_words(list_of_words)

# Solution
# Define a function which accepts a list as input
def list_of_words(words):
    print("Original list : ", words)
  # Initialize a variable 'count' to 0 to count the number of words
    count = 0
  # Use 'for' loop to iterate through each word of the list
  # Also check whether first and last character of each word is same using string indexing. If they are same increase the value of 'count' by 1
    for word in words:
        if len(word) > 1 and word[0] == word[-1]:
            count += 1
    return count

# Create a list of words
# Call the function and pass this list as parameter
print("First and the last letter words same as = ",list_of_words(['civic', 'organ', 'trust', 'rigid', 'erase', 'right']))

# Write a function to print the expensive orders
def expensive_orders(d,avg_val):
    result = {}
    for key, val in d.items():
        if val > avg_val :
            print(key,val)
expensive_orders({ "a": 3000,
                  "b": 200,
                  "c": 1050 }, 1000)

# Function to print the expensive orders
def expensive_orders(d, avg_val):
	result = {}
	for key, value in d.items():
		if value > avg_val:
			result[key] = value
	return result

expensive_orders({ "a": 3000,
                   "b": 200,
                   "c": 1050 }, 1000)



# Lesson 37
# The 'shuffler()' function to to jumble the letters of a word and form a jumbled word.
import random

def shuffler(word):
  letters = list(word)
  random.shuffle(letters)
  shuffled_word = ''.join(letters)
  return(shuffled_word)

shuffler('swim')

# Check whether player's guess is correct or not
# Printing the title 'GUESS A WORD GAME' center aligned
just_len = 100
print("guess a word game".upper().center(just_len, '-'))
print()
print("Rules____are____according____to____its____puzzle :  \n ")

# Get the player's name and store in a variable
player_name = input("\nWhat's your name?\n")

# Printing the terminate message 'Type 's' to stop the game at any time.'
print(f"\nType 's' to stop the game at any time.\n{'#' * just_len}")

# Creating the 'for' loop to shuffle the words in 'my_words' tuple and check the player's guess
for word in my_words:
    shuffled_word = shuffler(word)
    while shuffled_word == word:
        shuffled_word = shuffler(word)

  # Asking the user to 'Guess the word:' and store the word in a variable
    player_guess = input(f"Guess the correct Word : {shuffled_word.upper()} \n")

  # Convert the player guess to upper case using the 'upper()' function.
  # store the result in a variable 'player_guess_upper'
  # Write your code here
    player_guess.upper()
    player_guess_upper = []


  # If player enters 's' then terminate the 'for' loop using 'break' keyword
  # Write your code here
    if player_guess == 's':
        break


  # 'if player_guess_upper == word.upper():' print 'Correct!!' and increase the 'score' by 1.
  # Write your code here
    if player_guess == word.upper():
        print("Correct !")
        score= score + 1

  # Else print 'WRONG! Correct word is (correct_word)'
  # Write your code here
    else:
        print("Wrong !correct word is ",word)

# Display 'Game Over' and Final score to the player
print(f"Game Over! \n{player_name}, Your score is {score}.")



# Lesson 38
# Write a program to shuffle the name
import random

def shuffler(word):
    letters = str(word)
    new_word  = letters.split()
    new_word = list(reversed(new_word))
    shuffled_word = ' '.join(new_word)
    return(shuffled_word)

print(shuffler('Donald Trump'))
print()
print(shuffler("Rosie O'Donnell"))
print()
print(shuffler('Seymour Butts'))

# Write your solution here
import random

def shuffler(word):
    letters = list(word)
    random.shuffle(letters)
    letters.sort()
    shuffled_word = ''.join(letters)
    return(shuffled_word)

shuffler('hacker')



# Lesson 39
def form_date(text):
    for i in range(len(text)):
        my_new_str = text.split()
        new_form  = list(my_new_str)
        now_date = text[6:11] +  text[3:5] + text[0:2]
        return now_date
form_date("11/12/2019")

text = "01/15/2019"
text.split('/')

def form_date(text):
    str = text.split("/")
    str = "".join(str[2] + str[1] + str[0])
    return str
form_date("11/12/2019")



# Lesson 40
# Write your solution here to capitalise the first letter of every word
import re

def capitalize(s):
    return re.sub(r"[A-Za-z]+('[A-Za-z]+)?",
    lambda mo: mo.group(0)[0].upper() +mo.group(0)[1:].lower(),s)

text = "GOOD MORNING"
print(capitalize(text))

# Write your solution here
# import datetime module
import datetime
from datetime import date
# create a function which accepts two parameters, month and year
def para():
    # create a list containing weekdays from 'Monday' to 'Saturday'
    days = ['Monday', 'Tuesday','Wednesday','Thursday','Friday','Saturday']
    # use 'weekday()' function which returns an integer corresponding to the day of the week and store it in a variable 'day'.
    # use this 'day' variable as index in the above list and fetch the day name associated with this index
    day = date(2020,3,13).weekday()


    # check whether day fetched is Friday or not. If yes return True else False
    if day == 4:
        return True
    else:
        return False
# call the function
para()



# Lesson 41

# Lesson 42

# Lesson 43

# Lesson 44

# Write your solution here
def cap_space(text):
    new_text = ''

    for i, letter in enumerate(text):
        if i and letter.isupper():
            new_text += ' '

        new_text += letter
        print(new_text)

cap_space("helloworld")