# -*- coding: utf-8 -*-
"""practise 01 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADvot1EDVSuRXqBFEbz4GAWqHB6bBMok
"""

my_list = ["My","height","is",6,"feet"]
my_sent = " "
for items in my_list:
    items = str(items)
    my_sent = my_sent + " "+ items

my_sent

for i in range(1,15):
    print(""*(15-1)," "* (15+i),"#" * i,"#" * i)

for i in range(1,20):
    print(" "* (10-i)**2, i**2 * "#" )

for i in range(1,6):
    print(" "* (6-1),"#" * i)

def even_check(num):
    if (num%2) == 0:
        return "Even"
    else:
        return "Odd"
user_input = int(input("Enter a number : "))
even_check(user_input)

#  Create class 'Atom'. Add constructor and functions
class Atom:
  def __init__(self,name,protons,electrons,neutrons,electron_config):
    self.name = name
    self.electrons = electrons
    self.protons = protons
    self.neutrons = neutrons
    self.electron_config = electron_config

  def calculate_atomic_mass(self):
    atomic_mass = self.protons+self.neutrons
    return atomic_mass
  def calculate_charge(self):
    net_charge = self.protons - self.electrons
    if net_charge == 0:
      return 'Neutral'
    elif net_charge<0:
      return 'Anion'
    elif net_charge>0:
      return 'Cation'

# Create an object of 'Atom' class and call the functions
atom = Atom('Aluminium',13,13,14,[2,8,3])
print(atom.calculate_atomic_mass())
print(atom.calculate_charge())

# Create child class 'Element' and call the functions using the object of 'Element' class
class Element(Atom):
  def __init__(self,name,protons,electrons,neutrons,electron_config,mass,volume,boiling_point,melting_point):
    super().__init__(name,protons,electrons,neutrons,electron_config)
    self.mass = mass
    self.volume = volume
    self.boiling_point = boiling_point
    self.melting_point = melting_point

elem = Element('Aluminium',13,10,14,[2,8],10800,4,2743,933.5)
print(elem.calculate_atomic_mass())
print(elem.calculate_charge())

def multipication_table(n):
    sec_num = 1
    while sec_num < 11:
        print(n * sec_num)
        sec_num = sec_num +1
num = int(input("Enter a number"))
multipication_table(num)

i = 1
while True:
    factor = 2 ** i
    i = i +1
    print(factor)
    if factor == 4294967296:
       break

first_num = int(input("Enter a number "))
sec_num = 1
while sec_num < 11:
    print(first_num, " * ", sec_num, " = ", first_num * sec_num)
    sec_num = sec_num +1

factor = 1
while factor > 0:
    factor = factor * 5
    if factor == 5 ** 5:
        break
print(factor)

import numpy as np
import random

a = 100
square_root = np.sqrt(a)
print(square_root)

import random
def num():
    print("Random numbers between 1 to 100")
    lis = [random.randint(1,101) for i in range(0,100,5)]
    print(len(lis), "Numbers --->",lis)
num()

import random
a = random.randint(1,15)
a

for i in range(0,50):
    print(i+1)

def name(a,b,c,d):
    print(a,b,c,d)
name('kalyan','ajay','anand','manohar')