# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rp2GMyrmX9ASb5_ieH_6fH49gzFD3ASl
"""

# Import libraries
import pandas as pd

# Make a DataFrame
df = pd.DataFrame({'A': [0, 1, 2, 9, 4],
                   'B': [4, 9, 2, 0, 3],
                   'C': [8, 2, 7, 6, 8]})

# Perform the rolling window calculations with window size = 2
roll_mean = df.rolling(window = 2).mean()
print(roll_mean)