# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J11u2oFH1CyvtOPbAWY4h5m6Ddpd6hwn
"""

# Import Libraries
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({"A": ["one", "two", "three", "four", "five",
                         "six", "seven", "eight", "nine", "ten"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two", "one"],
                   "D": [11, 52, 83, 35, 43, 94, 25, 35, 79, 85],
                   "E": [22, 54, 45, 75, 96, 16, 38, 59, 65, 23]})

# Make a pivot table with values of 'D' and 'E' and index of 'A' and 'B'
genre_table = pd.pivot_table(df,values = ['D','E'], index =['A','B'],aggfunc = 'mean')

genre_table