# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8uYEY3kdE0fhG6tPTeAGY0IQltTDLbR
"""

# Import the necessary packages
import pandas as pd

# Create the DataFrames
df1 = pd.DataFrame({'name': ['John', 'Rohit', 'Riti', 'Michel'],
                    'age': [25, 26, 31, 28]})
df2 = pd.DataFrame({'name': ['John', 'Rohit', 'Riti', 'Michel'],
                    'sex': ['M', 'M', 'F', 'M']})

# Perform merging of dataframes using 'merge' function on 'name'
new_m = pd.merge(df1,df2,on = 'name')
new_m