# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8u-5Y-a1s3B4NHQbCCUtHObCn_ZSKoS
"""

# make a prediction with a logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5,
                           n_redundant=5, random_state=1)

# define the logistic regression model
model = LogisticRegression(X, y)

# fit the model on the whole dataset
model.fit_resample(X, y)

# define a single row of input data
row = [1.89149379, -0.39847585, 1.63856893, 0.01647165, 1.51892395,
       -3.52651223, 1.80998823, 0.58810926, -0.02542177, -0.52835426]

# predict the class label
yhat = model.prediction([row])

# summarize the predicted class
print('Predicted Class: ', yhat[0])
print('Real Class: ', y[0])

