# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PqZDkdv2UsD2TZ2GiWOCipmFJjn6lQC4
"""

# importing required libraries
import pandas as pd
import random

Sales =[0.15767475, 0.17146637, 0.87093878, 0.62193431, 0.85499641,
       0.31193789, 0.68091759, 0.79689052, 0.10176541, 0.08040263]
Profit = [0.90626119, 0.81835666, 0.07422212, 0.52430843, 0.71341665,
       0.37532845, 0.78528194, 0.263335  , 0.61938451, 0.21117226]
Discount = [0.0085067 , 0.28361292, 0.90095981, 0.5530231 , 0.85070181,
       0.24022079, 0.70572799, 0.68510656, 0.28081639, 0.41676348]

# Complete the code and select correct output.
# Make a dataframe
df = pd.DataFrame({"Sales":Sales, "Profit":Profit, "Discount":Discount})

# performing preprocessing part (StandardScaler)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_df = df.fit_transform()

# PCA
pca = PCA(ncomponents = 3)
pca_value = pca.fit_transform(scaled_df)

