# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17RevgHqjbzin-6VOEZye3XybwIOW51rM
"""

# Importing Libraries
import itertools

import warnings
warnings.filterwarnings("ignore")

# Choose the range for p, q and d
p = range(0, 3)
q = range(0, 3)
d = range(0, 3)

# Perform iterations on p, q and q variables
pdq_combination = list(itertools.product(p, d, q)) # return the list of all the computed tuple
print(pdq_combination[2,4])

# Print the combinations from index 2 to 4