# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYw6rqEG-3wmsa32JArgPH95Ci_fCsMV
"""

# Import the Libraries
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Year': [1995, 1997, 1999, 2001, 2003],
    'Sales (in %)': [98, 86.2, 65.5, 74, 90.3],
})

# Perform difference operation using `lambda` function
# Difference between 100 and Sales will give Loss
df['Year'] = df['Sales (in %)'].apply(lambda x: 100 - x)
df