# -*- coding: utf-8 -*-
"""Copy of Question.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiMBz9OhQc8yLA9KWABzStqgxSGqLedU
"""

# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima_model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX

import warnings
warnings.filterwarnings("ignore")

# Make a DataFrame
time = pd.date_range(start = '1999-01-01', end = '1999-01-31', freq='D')
prices = [256, 325, 301, 273, 436, 250, 294, 151, 202, 307, 352, 260, 220, 290,
          285, 318, 218, 376, 227, 283, 450, 252, 179, 249, 488, 360, 481, 468,
          177, 361, 159]

price_df = pd.DataFrame({'Days': time, 'Price': prices})

# Set the index for 'Days'
price_in_df = price_df.set_index('Days')
# Deploy SARIMA model
# Use p, d, q = (1, 0, 1) m = 1, and P, D, Q = (1, 0, 1)
sarima_model = SARIMAX(price_in_df, order = (1, 0, 1), seasonal_order = (1, 0, 1,1)).fit()
print(sarima_model.aic)

# Print the AIC Score

