# -*- coding: utf-8 -*-
"""Quiz114_1_soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVvnckpebYcrl0cRi6p-Y60LCd8IxMtx
"""

import numpy as np
random_data = np.array([
    [2, 5],
    [3, 3],
    [4, 8],
    [5, 7],
    [6, 2],
    [7, 4],
    [9, 11],
    [10, 12]
])

random_data

# Install 'pyclustertend' package
pip install pyclustertend

# Import 'hopkins' module
from pyclustertend import hopkins
# Get hopkins score for 'ranom_data' with 7 samples.
hopkins(random_data, 7)

"""---"""