# -*- coding: utf-8 -*-
"""Quiz118_4_soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN4NKpXIx0wBcxg5zGeOHtogCf-rk3vb
"""

import numpy as np

# 1D array
vector_a = np.array([[1, 4], [5, 6]])
vector_b = np.array([[2, 4], [5, 2]])

# Compute dot product of 'vector_a' and 'vector_b'
dot_prod = np.dot(vector_a, vector_b)
print("Dot Product  : \n", dot_prod)

"""---"""