# -*- coding: utf-8 -*-
"""Quiz117_2_soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxmUibiL3km96lGdfRnDHamtOgxmlPvC
"""

import numpy as np
# P1 vector
vec_P1 = np.array([1.76, 10.654, 98.635,  12.74, 6.87, 1.09, 9.23])
vec_P1

# Calculate the norm of a vector vec_P1
print('Norm of vector is: ', np.linalg.norm(vec_P1))

"""---"""