# -*- coding: utf-8 -*-
"""Quiz107_5_soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGHWpokydZpImTdN6qQxFLFULCA7FrTJ
"""

# Import the modules and generate the dataframe.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Generate a dataframe consisting of one column 'Diameters' having diameters of 9 balls.
gravity_df = pd.DataFrame({'Gravity': [8.9,	9.8,	1.6,	3.7, 9.0,	8.7]})
gravity_df.head()

# Import scikit learn KMeans library and determine the clusters.
from sklearn.cluster import KMeans
kmeans_1d = KMeans(n_clusters = 2, random_state = 2)
kmeans_1d.fit(gravity_df)
labels = kmeans_1d.predict(gravity_df)
print(labels)

"""---"""