# -*- coding: utf-8 -*-
"""Copy of IQuiz110.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGRwMH8yae50xV1KQ5KQc7edMNSc4iB0
"""

import pandas as pd
sr = pd.Series(['Naveen', 'Rahul', 'Sarah', 'Nitin', 'Neha'])
result = sr.str.contains(pat = 'N[a-e]')
result

"""---"""