# -*- coding: utf-8 -*-
"""Quiz118_soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbwyAUSE78-wlblPZgK5cpdICX7rmk3a
"""

import numpy as np

# create numpy 2d-array
m = np.array([[3, 12],
              [31, 23]])

print("Original square array:\n",m)

# Find eigenvalues and eigenvectors
eigen_val, eigen_vec = np.linalg.eig(m)

# print eigen values
print("Eigen values:\n",eigen_val)

# print eigen vectors
print("Eigenvectors:\n",eigen_vec)

"""---"""