# -*- coding: utf-8 -*-
"""random module  lesson 3 pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-FZ8MgROcWOQk2j6SXS5q04sbpIJGBX
"""

name = ("kalyan")

type(name)

m= 'kalyan', 'annand' ,' Rakesk'

print(m)

my_name = (kalyan,)

my= [('kalyan')]

type(my)

import random
def prediction():
  if count_zero>count_one:
    predict=1
  elif count_zero>count_one:
    predict=0
  else:
    predict=random.randint(0,1)
  return predict
def update_counts(player_input):
  global player_score ,computer_score
  if predicted==player_input:
    computer_score=computer_score + 1
  else:
    player_score =player_score + 1
def gameplay():
  valid_entries=["0","1"]
  while True:
    predicted= prediction
    player_input=input("Enter either 0 or 1:")
    while player_input not in valid_entries:
      print("Invalid!")
    palyer_input=input("Please enter either 0 or 1:")

# Uncomment below to take inputs from the user
a = float(input('Enter first side: '))
b = float(input('Enter second side: '))
c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f' %area)

rows = int(input("Enter number of rows: "))

for i in range(rows):
    for k in range(i+1):
        print("*", end = "  ")
    print("\n")

rows = int(input("Enter number of rows: "))

for i in range(rows, 0, -1):
    for j in range(0, i):
        print("* ", end=" ")

    print("\n")

k= 1
for i in range(1,k+1):
    for space in range(2, (rows+1)):
        print(k)

    k = 1
    print()

rows = int(input("Enter number of rows: "))

for i in range(rows, 0,+1):
    for j in range(1,i+1):
        print(j, end=" ")
        j = j +1
    print(j)

rows = int(input("Enter number of rows: "))

k = 0

for i in range(1, rows+1):
    for space in range(1, (rows-i)+1):
        print(end="  ")

    while k!=(2*i-1):
        print("* ", end="")
        k += 1

    k = 0
    print()

rows = int(input("Enter number of rows: "))

k = 1

for i in range(1,k+1):
    for space in range(2, (rows+1)):
        print(end="  ")

    k = 1
    print()

rows = int(input("Enter number of rows: "))

for i in range(rows,1):
    for space in range(0, rows-i):
        print("  ", end="")
    for j in range(2*i, i):
        print(" 1 ", end="")

rows = int(input("Enter number of rows: "))
coef = 1

for i in range(1, rows+1):
    for space in range(1, rows-i+1):
        print(" ",end="")
    for j in range(0, i):
        i = i+1
        print(i)
    print()

rows = int(input("Enter number of rows: "))
number = 1

for i in range(1, rows+1):
    for j in range(1, i+1):
        print(number, end=" ")
        number += 1
    print()

rows = int(input("Enter number of rows: "))

k = 0
count=0
count1=0

for i in range(1, rows+1):
    for space in range(1, (rows-i)+1):
        print(" ", end= "")
        count+=1

    while k!=((2*i)-1):
        if count<=rows-1:
            print(i+k, end="")
            count+=1
        else:
            count1+=1
            print(i+k-(2*count1), end=" ")
        k += 1

    count1 = count = k = 0
    print()

rows = int(input("Enter number of rows: "))

ascii_value = 65

for i in range(rows):
    for j in range(i+1):
        alphabet = chr(ascii_value)
        print(alphabet, end="   ")

    ascii_value += 1
    print("\n")