# -*- coding: utf-8 -*-
"""Copy of Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPHcvvUojupRX9BoCP3rXEg0Z9pQHC9z
"""

# Import the Libraries
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Year': [1995, 1997, 1999, 2001, 2003],
    'Sales (in %)': [98, 86.2, 65.5, 74, 90.3],
})

# Perform operation using `lambda` function
# Difference between 100 and Sales will give Loss
df['Loss (in %)'] = df['Sales (in %)'].apply(lambda x: 100-x)
df