# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0L83z4injTzSz30Q8Wpk16VyCCiIVO1
"""

# Import the Libraries
import pandas as pd
from ast import literal_eval

# Create DataFrames
df1 = "(2,3,4)"
df2 = "[2,3,4]"

# Convert strings into respective data type using `literal_eval`
df1_unstring = literal_eval(df1)
df2_unstring = literal_eval(df2)

# Print the type of unstringed DataFrame
print(type(df1_unstring))
print(type(df2_unstring))

