# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVf6GSS1ZBjDSOX7OXq5YurJ2bNbOb8b
"""

# Import the Libraries
from random import randrange
from pandas import Series
from statsmodels.tsa.seasonal import seasonal_decompose

import warnings
warnings.filterwarnings("ignore")

# Make a DataFrame
series = [i+randrange(10) for i in range(1,100)]

# Additive Decomposition
result = seasonal_decompose(series, model='additive', freq=1)

# Print 'trend' component
result.trend