# -*- coding: utf-8 -*-
"""Copy of Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPYoLNs_9CbZE0qiQn8npaeVNlbflCw9
"""

# Importing Libraries
import itertools

import warnings
warnings.filterwarnings("ignore")

# Choose the range for p, q and d
p = range(0, 3)
q = range(0, 3)
d = range(0, 3)

# Perform iterations on p, q and q variables
combinations = list(itertools.product(p, d, q))

# Print the combinations from index 2 to 4
print(combinations[2:5])