# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFzYlvZWsgOg_GFhxgpoUkOc2HE8Ubs_
"""

# Import libraries
import pandas as pd

# Make a DataFrame
df = pd.DataFrame({'A': [0, 1, 2, 9, 4],
                   'B': [4, 9, 2, 0, 3],
                   'C': [8, 2, 7, 6, 8]})

# Perform the rolling window calculations with window size = 2
df.rolling(2).sum()