# -*- coding: utf-8 -*-
"""Copy of Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fM7E9vEONaLKlYv5GhjuNwrfTJ-fxWHj
"""

12 % 5

10/2

odd = []

for i in range(0,1001):
    if (i % 2) != 0 and (i % 3) != 2 and (i % 4) == 3 and (i % 5) != 0 and (i % 5) != 2 and (i % 7) != 0:
        odd.append(i)
print(odd)


print(len(odd))

# Import libraries
import pandas as pd

# Make a DataFrame
df = pd.DataFrame({'A': [0, 1, 2, 9, 4],
                   'B': [4, 9, 2, 0, 3],
                   'C': [8, 2, 7, 6, 8]})

# Perform the rolling window calculations with window size = 2
df.rolling(2).sum()