# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eP7IUPVFkey27k2Zsv0YHKZBnr571w-c
"""

# Import the Libraries
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

# Make a Dummy DataFrame
time = pd.date_range(start = '1/1/1950', end = '31/12/1960', freq= 'Y')
values = [8347, 2832, 6574, 2974, 6728, 1923, 7132, 3741, 6196, 5193, 8253]
df = pd.DataFrame({'Year': time, 'Sales': values})

# Make 'Year' as index
df = df.set_index('Year')

# Perform first-order differencing
first_or_diff_df = df - df.shift(1)

# Perform second-order differencing
second_or_diff_df = first_or_diff_df - first_or_diff_df.shift(1)

# Print first 5 rows of seconf order differencing
second_or_diff_df.head()

