# -*- coding: utf-8 -*-
"""Copy of Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PqWVsLBdB46MkZufLbmszp59WcpBFtqw
"""

# Importing Packages
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Make a dataframe
X = pd.DataFrame(np.array(['M', 'O-', 'medium',
                           'M', 'O-', 'low',
                           'F', 'O+', 'high',
                           'F', 'AB', 'medium',
                           'F', 'B+', 'low']).reshape((5,3)))

# Add column names
X.columns = ['sex', 'blood_type', 'edu_level']

# Perform Label Encoding for 'edu_level' column.
encoder = LabelEncoder()

X['edu_level'] = encoder.fit_transform(X['edu_level'])
print(X['edu_level'])