# -*- coding: utf-8 -*-
"""Solution of Ques 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11b3u9U8IYGRCggu346DH_RcSvwydms_m
"""

import pandas as pd
import numpy as np

A = ['Cold', 'Hot', 'Warm', 'Cold', 'Cold', 'Warm']
B = ['High', 'High', 'Medium', 'Medium', 'High', 'Low']
C = ['Pleasent', 'Hot', 'Hot', 'Pleasent', 'Pleasent', np.nan]

# Complete the code and select correct output.
# Make a dataframe
df = pd.DataFrame({"Temperature":A, "Humidity":B, "C":C})

# Convert categorical column to numerical one.
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

for column in df.columns:
  df[column] = label.fit_transform(df[column])

# TCalculate euclidean distance between each data point.
from sklearn.metrics.pairwise import nan_euclidean_distances

dist = nan_euclidean_distances(df, df)
dist_df = pd.DataFrame(dist)
dist_df

