# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQeiPyr7R7qQt06KTcY2QpZ2bqR7x6SI
"""

# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima_model import ARIMA

import warnings
warnings.filterwarnings("ignore")

# Make a DataFrame
time = pd.date_range(start = '1999-01-01', end = '1999-01-31', freq='D')
prices = [130, 142, 142, 161, 169, 193, 206, 249, 271, 289, 301, 313,
          315, 322, 327, 332, 342, 345, 349, 354, 370, 382, 426, 434,
          442, 445, 462, 466, 472, 496, 498]
price_df = pd.DataFrame({'Days': time, 'Price': prices})

# Set the index for 'Days'
price_ind_df = price_df.set_index('Days')

# Build ARIMA model using entire dataset.
# Set p = 1, d = 1, q = 0
ar_model = ARIMA(price_ind_df, order = (1, 1, 0)).fit()

# Predict using `predict()` and print first 5 observations
pred = ar_model.predict(1, len(price_ind_df) - 1, typ = 'levels' )
print(pred[:5])

