# -*- coding: utf-8 -*-
"""sum_series Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGuImparMHuIzlIU0NqSupt-LzteBv4O
"""

L = [[0, 210], [1, 198], [2, 188], [3, 173], [4, 240]]
mList = []
for element in L:
    mList = mList +L[-1]
    mList

2 = 3

import matplotlib.pyplot as plt

a = ['English','Maths','Hind','computer','Telugu']
b = [90,80,78,89,90]
plt.figure(figsize=(20,5))
plt.bar(a,b,color = a)
plt.show()

# Print n -digit number
def num_generator(n):
  req_num=0
  count=n - 1
  while count>=1:
    req_num=req_num + (10** count) * n
    count=count -1
  return req_num
for n in range(1,10):
    print(num_generator(n), "=", n)

for row in range(3):
    for col in range(3+1):
        b = b + 1
        print(b)

f

import numpy as np
def sum_series(number):
    num = 1
    while num <= number:
        sum = 0
        num_list = []
        for i in range(num):
            sum = sum +(num*pow(10,i))
            num_list.append(sum)

        num_array= np.array(num_list)
        print(num_array.sum())
        num = num+1
sum_series(10)

list = 44+30+ 87+38+71+36
mean = list /6
print(mean)

48.86**2