# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGYQIs-8BFroTBUdwCHmlTlMVRdBVtqQ
"""

import numpy as np
import matplotlib.pyplot as plt
from mplfinance import candlestick_ohlc as m

a = [10,20,30,40,50,60]
b = [4,8,16,24,32,40]
plt.figure(figsize=(10,8),dpi = 96)
.candlestick_ohlc(a,width=0.2, alpha=1.0)

plt.show()

import matplotlib.pyplot as plt
import yfinance as yf

import pandas as pd

import matplotlib.dates as mpdates


plt.style.use('dark_background')

# extracting Data for plotting

df = pd.read_csv('data.csv')

df = df[['Date', 'Open', 'High',

         'Low', 'Close']]

# convert into datetime object

df['Date'] = pd.to_datetime(df['Date'])

# apply map function

df['Date'] = df['Date'].map(mpdates.date2num)

# creating Subplots

fig, ax = plt.subplots()

# plotting the data

candlestick_ohlc(ax, df.values, width = 0.6,

                 colorup = 'green', colordown = 'red',

                 alpha = 0.8)

# allow grid

ax.grid(True)

# Setting labels

ax.set_xlabel('Date')

ax.set_ylabel('Price')

# setting title

plt.title('Prices For the Period 01-07-2020 to 15-07-2020')

# Formatting Date

date_format = mpdates.DateFormatter('%d-%m-%Y')
ax.xaxis.set_major_formatter(date_format)
fig.autofmt_xdate()

fig.tight_layout()

# show the plot
plt.show()