# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0THoCZEj8VdWTs93nYq6OadFl7E4qi9
"""

word = "green vegetables"
print(word.find('g',2))

print(word.find('veg',2))

print(word.find('tab',4,15))

num = 25
def compute():
    num = 20
    print(num,end=' ')

compute()
print(num)



def compute(x, y):
    return str(x) +
str(len(y))
m = compute(25,
    'mycstutorial')
print(m)